"""Реестр флагов (6.7)."""
LATE = "LATE"
EARLY_DEPARTURE = "EARLY_DEPARTURE"
ABSENCE_GAP = "ABSENCE_GAP"
MISSED_DAY = "MISSED_DAY"
OFF_SHIFT_ATTENDANCE = "OFF_SHIFT_ATTENDANCE"
ACTIVITY_REQUIRES_REVIEW = "ACTIVITY_REQUIRES_REVIEW"
SESSION_OPEN = "SESSION_OPEN"

ALL = (LATE, EARLY_DEPARTURE, ABSENCE_GAP, MISSED_DAY, OFF_SHIFT_ATTENDANCE,
       ACTIVITY_REQUIRES_REVIEW, SESSION_OPEN)
