"""Реестр кодов Reason (6.2)."""
OPENING_ROUNDED = "OPENING_ROUNDED"
PLAN_EQUALS_FACT = "PLAN_EQUALS_FACT"
UNPAID_CREDITED = "UNPAID_CREDITED"
CODE_PLACED = "CODE_PLACED"
NO_RECEIVER = "NO_RECEIVER"
BANK_APPLIED = "BANK_APPLIED"
CODE_CUT = "CODE_CUT"
RESIDUAL_CARRIED = "RESIDUAL_CARRIED"

PASS_PRIMARY = "primary"
PASS_AFTER_CASCADE = "after_cascade"

ALL = (OPENING_ROUNDED, PLAN_EQUALS_FACT, UNPAID_CREDITED, CODE_PLACED, NO_RECEIVER,
       BANK_APPLIED, CODE_CUT, RESIDUAL_CARRIED)
